apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
     labels:
       app: frontend
    spec:
     containers:
     - name: frontend
       image: gnishanth444/k8-micro-services:frontend-ui-0.0.4
       ports:
       - containerPort: 8080
       resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
   - port: 8080
     targetPort: 8080
     nodePort: 30009
  type: NodePort
                   
